Parameters: 
  masterUsername: 
    Type: String
    Description: Number of shards for user stream

  masterPassword: 
    Type: String
    Description: Number of shards for utm stream
  myVPC: 
    Type: String
    Description: VPC ID

Resources:
    InstanceSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
          GroupDescription: Grant Kinesis Data Firehose access to your Amazon Redshift cluster
          VpcId:
             Ref: myVPC
          SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 5439
            ToPort: 5439
            CidrIp: 52.70.63.192/27    


    RedshiftCluster:
        Type: "AWS::Redshift::Cluster"
        Properties:
            ClusterIdentifier: "redshift-cluster-1"
            ClusterType: single-node
            NodeType: "dc2.large"
            MasterUsername: 
                 Ref: masterUsername
            MasterUserPassword: 
                 Ref: masterPassword
            DBName: "tracking"
            Port: 5439
            AutomatedSnapshotRetentionPeriod: 1
            VpcSecurityGroupIds: 
                - !GetAtt InstanceSecurityGroup.GroupId
            ClusterSubnetGroupName: "default"
            AvailabilityZone: !Sub "${AWS::Region}b"
            PreferredMaintenanceWindow: "sun:00:00-sun:00:30"
            ClusterVersion: "1.0"
            AllowVersionUpgrade: true
            PubliclyAccessible: true
            Encrypted: false
